### ISSUE TITLE
Version number update

### ISSUE THREAD

**Issue by sos4nt** [ruby/base64#15]
I've just noticed, that the current version number (0.1.1) still starts with a zero, indicating a development version with unstable public API. Since this is rather mature code, you might consider a 1.x release (or 3.x to match Ruby).

**Comment by hsbt** [comment]
>indicating a development version with unstable public API. 

I know a few people rely on this policy. But `base64` don't use this versioning policy. You can use 0.x.y for produciton use.

**Comment by perlun** [comment]
I also noted this @sos4nt. :thinking: Since [SemVer](https://semver.org/) is so prevalent (and IMO for good reasons), perhaps adding a note about the fact you describe here to the top-level README file would make sense @hsbt? Just to minimize the confusion.

(I got here since I ran into the warning that `base64` will no longer be included in the standard gems in Ruby 3.4, triggered by this lib in my dependency graph: https://github.com/dtao/safe_yaml/issues/108)
